# fly.toml app configuration file generated for upkeepbot on 2026-05-09T07:55:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'upkeepbot'
primary_region = 'lhr'

[build]

[deploy]
  release_command = 'node register.js'

[env]
  UPKEEP_DB_PATH = '/data/upkeep.db'

[[mounts]]
  source = 'upkeep_data'
  destination = '/data'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
